import { 
  PlayerProfile, 
  DailyQuest, 
  DungeonGate, 
  ShadowSoldier, 
  CraftItem, 
  ShopItem, 
  LeaderboardHunter, 
  SystemNotification 
} from '@/types/system';

export const initialPlayerProfile: PlayerProfile = {
  id: 'hunter-001',
  name: 'KAIEN JIN',
  rank: 'E',
  level: 1,
  job: 'None',
  title: 'The Weakest Hunter',
  hp: 240,
  maxHp: 240,
  mp: 120,
  maxMp: 120,
  fatigue: 15,
  maxFatigue: 100,
  exp: 65,
  maxExp: 100,
  stats: {
    str: 10,
    agi: 10,
    vit: 10,
    int: 10,
    per: 10,
  },
  availablePoints: 3,
  combatPower: 145,
  gold: 750,
  restTokens: 2,
  streakDays: 4,
  shadowCount: 3,
  penaltiesIssued: 0,
  penaltyActive: false,
  penaltyTimeRemaining: 0,
  awakenedAt: '2026-09-01T06:00:00Z',
};

export const initialDailyQuest: DailyQuest = {
  id: 'daily-quest-today',
  title: 'QUEST: PREPARATIONS FOR STRENGTH',
  description: '[The System demands daily physical conditioning. Failure will result in punitive teleportation to the Penalty Zone.]',
  timeRemainingSeconds: 7420, // ~2 hours remaining
  allCompleted: false,
  claimed: false,
  tasks: [
    {
      id: 'task-pushups',
      name: 'Push-ups',
      target: 20,
      current: 0,
      unit: 'reps',
      completed: false,
      expReward: 60,
    },
    {
      id: 'task-situps',
      name: 'Sit-ups',
      target: 20,
      current: 0,
      unit: 'reps',
      completed: false,
      expReward: 60,
    },
    {
      id: 'task-squats',
      name: 'Squats',
      target: 20,
      current: 0,
      unit: 'reps',
      completed: false,
      expReward: 60,
    },
    {
      id: 'task-running',
      name: 'Endurance Run',
      target: 2,
      current: 0,
      unit: 'km',
      completed: false,
      expReward: 70,
    },
  ],
};

export const initialDungeons: DungeonGate[] = [
  {
    id: 'gate-e-1',
    name: 'Goblin Outpost Gate',
    rank: 'E',
    type: 'gate',
    description: '[Low density anomaly. Basic goblin infantry. Ideal for novice awakening calibration.]',
    recommendedLevel: 1,
    bossName: 'Hobgoblin Brute',
    bossHp: 100,
    bossMaxHp: 100,
    timeLimitSeconds: 600,
    rewards: {
      exp: 120,
      gold: 400,
      shadowExtractable: 'Shadow Goblin Scout',
    },
    cleared: false,
  },
  {
    id: 'gate-d-1',
    name: 'Sunken Crypt of the Cursed',
    rank: 'D',
    type: 'dungeon',
    description: '[High-gravity dungeon. Muscular endurance testing. Undead resistance high.]',
    recommendedLevel: 6,
    bossName: 'Blood Knight Commander',
    bossHp: 250,
    bossMaxHp: 250,
    timeLimitSeconds: 900,
    rewards: {
      exp: 350,
      gold: 1200,
      shadowExtractable: 'Shadow Blood Sentinel',
    },
    cleared: false,
  },
  {
    id: 'gate-c-1',
    name: 'Steel Scorpion Cavern',
    rank: 'C',
    type: 'gate',
    description: '[Intense metabolic threshold. High-intensity interval combat.]',
    recommendedLevel: 14,
    bossName: 'Chitin Empress',
    bossHp: 600,
    bossMaxHp: 600,
    timeLimitSeconds: 1200,
    rewards: {
      exp: 900,
      gold: 3500,
    },
    cleared: false,
  },
  {
    id: 'gate-b-1',
    name: 'Cerberus Volcanic Chasm',
    rank: 'B',
    type: 'dungeon',
    description: '[Thermal endurance zone. Heart rate must remain sustained in zone 4.]',
    recommendedLevel: 25,
    bossName: 'Triple-Headed Hellhound',
    bossHp: 1400,
    bossMaxHp: 1400,
    timeLimitSeconds: 1500,
    rewards: {
      exp: 2400,
      gold: 9000,
      shadowExtractable: 'Cerberus Shadow Beast',
    },
    cleared: false,
  },
  {
    id: 'gate-a-1',
    name: 'High Orc Citadel',
    rank: 'A',
    type: 'dungeon',
    description: '[Elite war party. Heavy compound lift challenge.]',
    recommendedLevel: 40,
    bossName: 'Kargalgan the Shaman',
    bossHp: 3200,
    bossMaxHp: 3200,
    timeLimitSeconds: 1800,
    rewards: {
      exp: 6000,
      gold: 25000,
    },
    cleared: false,
  },
  {
    id: 'gate-s-1',
    name: 'Architect Abyss Gate',
    rank: 'S',
    type: 'boss',
    description: '[Monarch level singularity. Extreme mental and physical annihilation threshold.]',
    recommendedLevel: 60,
    bossName: 'Monarch of White Flames',
    bossHp: 10000,
    bossMaxHp: 10000,
    timeLimitSeconds: 2400,
    rewards: {
      exp: 25000,
      gold: 100000,
      shadowExtractable: 'Abyssal General Igris-Type',
    },
    cleared: false,
  },
];

export const initialShadowArmy: ShadowSoldier[] = [
  {
    id: 'shadow-1',
    name: 'Shadow Runner',
    title: 'The Tireless Vanguard',
    habit: '5km Morning Run',
    streak: 18,
    power: 1240,
    rank: 'C',
    unlocked: true,
    quote: '[My stride shall carve paths through endless stone.]',
    iconType: 'speed',
  },
  {
    id: 'shadow-2',
    name: 'Shadow Sleeper',
    title: 'Warden of Restoration',
    habit: '8hr Deep Recovery',
    streak: 24,
    power: 1850,
    rank: 'B',
    unlocked: true,
    quote: '[In silent slumber, cellular regeneration achieves perfection.]',
    iconType: 'sleep',
  },
  {
    id: 'shadow-3',
    name: 'Shadow Hydrator',
    title: 'Aqua Elemental',
    habit: '3.5L Daily Hydration',
    streak: 31,
    power: 2400,
    rank: 'A',
    unlocked: true,
    quote: '[The blood streams pure with unyielding fluid power.]',
    iconType: 'water',
  },
  {
    id: 'shadow-4',
    name: 'Shadow Ironclad',
    title: 'Titan of Heavy Steel',
    habit: '100 Daily Push-ups',
    streak: 7,
    power: 780,
    rank: 'D',
    unlocked: false,
    quote: '[No gravity can bend a spine forged in repetition.]',
    iconType: 'shield',
  },
  {
    id: 'shadow-5',
    name: 'Shadow Sage',
    title: 'Disciplined Mind',
    habit: '20m Post-Workout Focus',
    streak: 12,
    power: 990,
    rank: 'C',
    unlocked: false,
    quote: '[The muscle is nothing without the cold focus that commands it.]',
    iconType: 'mind',
  },
  {
    id: 'shadow-6',
    name: 'Shadow Monarch Marshal',
    title: 'Supreme Commander',
    habit: '100% 60-Day Habit Mastery',
    streak: 0,
    power: 9999,
    rank: 'S',
    unlocked: false,
    quote: '[ARISE. The world bends to our discipline.]',
    iconType: 'blade',
  },
];

export const initialCraftItems: CraftItem[] = [
  {
    id: 'craft-rest-token',
    name: 'Rest Token',
    description: '[Excuses a single missed Daily Quest without invoking the Penalty Zone. Protects streak.]',
    rarity: 'Common',
    readyToCraft: true,
    resultIcon: 'ShieldAlert',
    ingredients: [
      { id: 'ing-1', name: 'Iron Will Core', count: 3, required: 2, icon: 'Flame' },
      { id: 'ing-2', name: 'Recovery Essence', count: 2, required: 1, icon: 'Droplets' },
      { id: 'ing-3', name: 'Discipline Shard', count: 5, required: 3, icon: 'Sparkles' },
    ],
  },
  {
    id: 'craft-streak-shield',
    name: 'Streak Aegis',
    description: '[Passive barrier that automatically absorbs a failed workout day.]',
    rarity: 'Rare',
    readyToCraft: false,
    resultIcon: 'ShieldCheck',
    ingredients: [
      { id: 'ing-4', name: 'Void Thread', count: 1, required: 2, icon: 'GitBranch' },
      { id: 'ing-5', name: 'Titan Bone Powder', count: 4, required: 4, icon: 'Activity' },
      { id: 'ing-6', name: 'Mana Crystal', count: 2, required: 3, icon: 'Zap' },
    ],
  },
  {
    id: 'craft-exp-booster',
    name: 'Monarch EXP Surge (+50%)',
    description: '[Doubles all EXP earned from the next 3 completed dungeon gates or quests.]',
    rarity: 'Epic',
    readyToCraft: true,
    resultIcon: 'TrendingUp',
    ingredients: [
      { id: 'ing-7', name: 'Abyssal Catalyst', count: 2, required: 1, icon: 'Radio' },
      { id: 'ing-8', name: 'Runed Quicksilver', count: 3, required: 2, icon: 'Clock' },
      { id: 'ing-9', name: 'Blood Ruby', count: 4, required: 3, icon: 'HeartPulse' },
    ],
  },
  {
    id: 'craft-elixir-life',
    name: 'Elixir of Sovereign Life',
    description: '[Instantly eliminates all physical fatigue (Fatigue -> 0), restores 100% HP and MP.]',
    rarity: 'Legendary',
    readyToCraft: false,
    resultIcon: 'FlaskConical',
    ingredients: [
      { id: 'ing-10', name: 'Tear of the Monarch', count: 0, required: 1, icon: 'Crown' },
      { id: 'ing-11', name: 'Pure Mana Core', count: 2, required: 5, icon: 'Sparkle' },
      { id: 'ing-12', name: 'Celestial Herb', count: 1, required: 3, icon: 'Feather' },
    ],
  },
];

export const initialShopItems: ShopItem[] = [
  {
    id: 'shop-theme-purple',
    name: 'Monarch Sovereign Violet',
    category: 'Theme',
    price: 1200,
    description: '[Reconfigures HUD aura to deep cosmic violet with monarch particle flairs.]',
    previewColor: '#8B2CFF',
    owned: false,
    equipped: false,
  },
  {
    id: 'shop-theme-blood',
    name: 'Crimson Berserker Aura',
    category: 'Theme',
    price: 1500,
    description: '[Envelops all System windows in intimidating hyper-red battle energy.]',
    previewColor: '#FF2D4B',
    owned: false,
    equipped: false,
  },
  {
    id: 'shop-frame-sovereign',
    name: 'Obsidian Monarch Frame',
    category: 'Frame',
    price: 2000,
    description: '[Holographic window frame with obsidian horned crowns and electric arcs.]',
    owned: false,
    equipped: false,
  },
  {
    id: 'shop-title-arise',
    name: 'Title: [Architect of Shadows]',
    category: 'Title',
    price: 800,
    description: '[Display title visible to all guild members and global leaderboard.]',
    owned: true,
    equipped: true,
  },
  {
    id: 'shop-sound-voice',
    name: 'Vocal System Synthesizer',
    category: 'Soundpack',
    price: 2500,
    description: '[Cold synthetic female AI voice announcement for all quest alerts.]',
    owned: false,
    equipped: false,
  },
];

export const initialLeaderboard: LeaderboardHunter[] = [
  {
    id: 'lb-1',
    name: 'THOMAS_ANDREWS',
    rank: 'National',
    level: 98,
    combatPower: 84200,
    title: 'Goliath of the West',
    job: 'Dreadnought Berserker',
    guild: 'Scavengers',
    change: 'same',
  },
  {
    id: 'lb-2',
    name: 'LIU_ZHIGANG',
    rank: 'National',
    level: 95,
    combatPower: 79500,
    title: 'Blade of the East',
    job: 'Aegis Knight',
    guild: 'Dragon Guild',
    change: 'same',
  },
  {
    id: 'lb-3',
    name: 'CHA_HAE_IN',
    rank: 'S',
    level: 82,
    combatPower: 58900,
    title: 'The Radiant Dancer',
    job: 'Void Assassin',
    guild: 'White Tiger',
    change: 'up',
  },
  {
    id: 'lb-4',
    name: 'BAEK_YOON_HO',
    rank: 'S',
    level: 79,
    combatPower: 54100,
    title: 'White Tiger Lord',
    job: 'Dreadnought Berserker',
    guild: 'White Tiger',
    change: 'down',
  },
  {
    id: 'lb-5',
    name: 'CHOI_JONG_IN',
    rank: 'S',
    level: 76,
    combatPower: 51200,
    title: 'The Ultimate Flame',
    job: 'Phantom Ranger',
    guild: 'Hunters Guild',
    change: 'same',
  },
  {
    id: 'lb-6',
    name: 'KAIEN JIN (YOU)',
    rank: 'E',
    level: 1,
    combatPower: 145,
    title: 'The Weakest Hunter',
    job: 'None',
    guild: 'Solo',
    change: 'up',
  },
];

export const initialNotifications: SystemNotification[] = [
  {
    id: 'notif-1',
    title: '[SYSTEM AWAKENING COMPLETE]',
    message: 'A Player has been registered into the Sovereign Matrix. Welcome, Hunter Kaien.',
    type: 'info',
    timestamp: 'Just now',
    read: false,
  },
  {
    id: 'notif-2',
    title: '[DAILY QUEST ISSUED]',
    message: 'Preparations for Strength is now active. Time limit: Midnight.',
    type: 'warning',
    timestamp: '2h ago',
    read: false,
  },
  {
    id: 'notif-3',
    title: '[NEW SHADOW REGISTERED]',
    message: 'Shadow Hydrator has reached a 30-day consistency streak! Power +500.',
    type: 'success',
    timestamp: '1d ago',
    read: true,
  },
];
